spring:
  mail:
      host: smtp.gmail.com
      port: 587
      username: beworm.readedbooks@gmail.com
      password: al199315al
      properties.mail.smtp:
        starttls.enable: true
        starttls.required: true
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000