spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mybooks}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    include: 'email'
logging.level.org.hibernate.SQL: debug
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
