spring:
  datasource:
    url: jdbc:postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
  profiles:
    include: 'email'
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  image:
    url: "https://myspringbooks.herokuapp.com/v1/img/"
  verify:
    userId: ${USER_ID}
    secret: ${USER_SECRET}
    email:
      url: "https://myspringbooks.herokuapp.com/v1/users/verify/"
    redirect:
      url: "https://pavelevleev.github.io/"
logging.level.org.hibernate.SQL: debug
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR

#liquibase:
#  change-log: classpath:db/changelog/db.changelog-master.xml
