spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mybooks}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: beworm.readedbooks@gmail.com
    password: al199315al
    properties.mail.smtp:
      starttls.enable: true
      starttls.required: true
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000




logging.level.org.hibernate.SQL: debug
